config/routes.rb
Rails.application.routes.draw do
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new'
  post '/articles' => 'articles#create', as: 'article_create'
  get '/articles/:id/show' => 'articles#show', as: 'article_show'
  get '/articles/:id/edit' => 'articles#edit', as: 'article_edit'
  put '/articles/:id/update' => 'articles#update', as: 'article_update'
  delete '/articles/:id' => 'articles#delete', as: 'article_delete'
  # get 'articles/show'
  # get 'articles/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :heading, presence: true,
                        length: { maximum: 50 }

    validates :subheading, presence: true

    validates :body, presence: true,
                     length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to article_show_path
    else
      render :edit
    end
  end

  def delete
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:heading, :subheading, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container masthead">
  <%= form_with method: :put, scope: :article, url: article_update_path, local: true do |f| %>
    <p>
      <% if @article.errors.any? %>
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li class= "text-danger list-unstyled">ERROR : <%= message %></li>
          <% end %>
        </ul>
      <% end %> 
    </p>
    </br>
    <div class="form-floating mb-3">
      <label for="floatingInput"><%= f.label :heading %></label><br/>
      <%= f.text_field :heading, class: 'form-control' %>
    </div>
    </br>
    <div class="form-floating">
      <label for="floatingInput"><%= f.label :subheading %></label><br/>
      <%= f.text_field :subheading, class: 'form-control' %>
    </div>
    </br>
    <div class="form-group">
      <label for="comment"><%= f.label :body %></label>
      <%= f.text_area :body, class: 'form-control', size: '40x10', id: 'comment' %>
    </div>
    </br>
    <p>
        <%= f.submit "Update", class: 'btn btn-primary' %>
        <%= link_to 'Go Back', articles_path, class: 'btn btn-default pull-right' %>
    </p>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="column col-sm-9" id="main">
  <div class="padding">
    <div class="full col-sm-9">
      <div class="col-sm-12">  
        <div class="page-header text-muted divider">
          BLOGS
        </div>
      </div>   
      <% @articles.each do |article| %>
        <div class="row">    
          <div class="col-sm-10">
            <h4>
              <span class="label label-default">
                Article No.  <%= article.id %>
              </span>
            </h4>
            <h3>
              <%= article.heading.upcase %>
            </h3>
            <h3>
              <small>
                <%= truncate(article.subheading, length: 55) %>
              </small>
            </h3>
            <h4>
              <span class="text-muted"><small><i>
                <%= article.created_at.strftime("%B %e, %Y at %l:%M %p UTC") %>
                • Updated <%= time_ago_in_words(article.updated_at) %> ago
              </span></i></small></br></br>
                <%= link_to "Read More", article_show_path(article), class: 'btn btn-primary' %>
            </h4>
          </div>
          
          <div class="col-sm-2">
            <%= link_to article_delete_path(article), class: 'btn btn-danger pull-right', method: :delete, data: { confirm: 'Delete this article?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>

            <%= link_to article_edit_path(article), class: 'btn btn-warning pull-right' do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>   
          </div> 
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container masthead">
  <%= form_with method: :post, scope: :article, url: article_create_path, local: true do |f| %>
    <p>
      <% if @article.errors.any? %>
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li class= "text-danger list-unstyled">ERROR : <%= message %></li>
          <% end %>
        </ul> 
      <% end %> 
    </p>
    </br>
    <div class="form-floating mb-3">
      <label for="floatingInput"><%= f.label :heading %></label><br/>
      <%= f.text_field :heading, class: 'form-control' %>
    </div>
    </br>
    <div class="form-floating">
      <label for="floatingInput"><%= f.label :subheading %></label><br/>
      <%= f.text_field :subheading, class: 'form-control' %>
    </div>
    </br>
    <div class="form-group">
      <label for="comment"><%= f.label :body %></label>
      <%= f.text_area :body, class: 'form-control', size: '40x10', id: 'comment' %>
    </div>
    </br>
    <p>
        <%= f.submit "Post", class: 'btn btn-primary' %>
        <%= link_to 'Go Back', articles_path, class: 'btn btn-default pull-right' %>
    </p>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container masthead">
  <div class="row">
    <h1 class="mt-4"><%= @article.heading %></h1>
    <hr>
    <p>
      <%= @article.created_at.strftime("%B %e, %Y at %l:%M %p UTC") %>
      •  Updated <%= time_ago_in_words(@article.updated_at) %> ago
    </p>
    <hr>
    <p class="lead">
      <%= @article.subheading %>
    </p>
    <p>
      <%= simple_format(@article.body)  %>
    </p>
    <hr>
  </div>

  <p>
    <%= link_to 'Edit', article_edit_path, class: "btn btn-warning" %>
    <%= link_to 'Delete', article_delete_path, class: 'btn btn-danger pull-right', method: :delete, data: { confirm: 'Delete this article?' } %>
    <%= link_to 'Go Back', articles_path, class: "btn btn-default" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    
      <%= render template: 'layouts/header.html.erb' %>            
      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-default" href="#">
        BLOG APP
      </span>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <span>
          <%= link_to 'Home', articles_path, class: 'navbar-brand' %>
        </span>
        <span>
          <%= link_to 'Create Blog', articles_new_path, class: 'btn btn-success' %>
        </span>
      </li>
    </ul>
  </div>
</nav>